Added files via upload
now correctly catches flags that won't work
improved formatting

diff --git a/screenr b/screenr
--- a/screenr
+++ b/screenr
@@ -52,7 +52,7 @@ exit 0
 }
 
 function version {
-        echo "screenr - v1.2"
+        echo "screenr - v1.2.1"
         echo "https://github.com/Lochverstaerker/screenr"
         exit 0
 }
@@ -253,23 +253,30 @@ while test $# -gt 0; do
             save_flag=1
             shift
             ;;
-        --format|-t|--thumb) #catch some flags that won't work in maim/scrot
-            if [[ $1 == "--format" && $scrot_flag != "1" ]]; then
-                echo "$1 is currently unsupported." >&2
-                echo "Please choose your format in screenr's config file. Aborting" >&2
-                exit 1
-            elif [[ $1 != "--format" && $scrot_flag == "1" ]]; then
-                echo "$1 is currently unsupported. Aborting" >&2
-                exit 1
-            else
-                break
-            fi
-            ;;
         *)
             break
             ;;
     esac
 done
+
+# Act on some flags that won't work with maim/scrot
+if [[ $(echo "$@" | grep -E -e "--format") && $scrot_flag != "1" ]]; then
+    echo "--format is currently unsupported." >&2
+    echo "Please choose your format in screenr's config file. Aborting" >&2
+    exit 1
+elif [[ $(echo "$@" | grep -E -e"--thumb|-t") && $scrot_flag == "1" ]]; then
+    echo "-t|--thumb is currently unsupported. Aborting" >&2
+    exit 1
+fi
+
+# Catch some scrot flags that would not work properly
+if [[ $scrot_flag == "1" ]]; then
+    if [[ $(echo "$@" | grep -E -e "-h") ]]; then
+        usage
+    elif [[ $(echo "$@" | grep -E -e "-v") ]]; then
+        version
+    fi
+fi
 
 mkdir "/tmp/screenr" #directory where temporary files will be created; removed at the end of the script during cleanup
 image_name=$(date "$date_format")."$img_format" #Name of the image file
@@ -281,6 +288,7 @@ full_path=/tmp/screenr/"$image_name" #Full path to the image file
 if [[ $(echo "$@ " | grep -e '-s \|--select') ]]; then
     selection_mode=1
 fi
+
 take_screenshot "$@"
 
 # Acts on specified flags and if none were passed it goes to menu to let user decide manually
